# Increase history limit
set-option -g history-limit 30000

# In copy-mode also copy into X (but no wayland!)
bind -T copy-mode-vi y send -X copy-pipe "xclip -selection c"

# Needed for time tracker app
set-option -g set-titles on
set-option -g set-titles-string "#S[#W]#(parse_git_branch)#T"
set-option -g set-titles-string "#S[#W] / #T"
